# Generated by Django 4.1.2 on 2022-11-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_image_alter_book_last_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
